[book]
authors = ["Vishnu Reddy"]
language = "en"
src = "src"
title = "test_examples"

[output.html]
additional-css = ["mdbook_plugin/visualization.css", "theme/playground.css"]
additional-js = ["mdbook_plugin/helpers.js", "theme/playground.js"]
